apiVersion: v1
kind: Pod
metadata:
  namespace: aap
  labels:
    ansible_job: ''
spec:
  serviceAccountName: default
  automountServiceAccountToken: false
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: ansible_job
                  operator: Exists
            topologyKey: kubernetes.io/hostname
  containers:
    - image: >-
        registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9@sha256:2534d07f1ae41af32adb681e283cbaea465cbe0f9d234ed5478a7bfad7676e7f
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      resources:
        requests:
          cpu: 250m
          memory: 100Mi
      volumeMounts:
        - name: aap-api 
          mountPath: /tmp/aap-api
  volumes:
    - name: aap-api
      secret:
        secretName: aap-api
        items:
          - key: key 
            path: key
